### ISSUE TITLE
Broken Links to External Resources

### ISSUE THREAD

**Issue by McGroggin** [The-Modular-Mind/oscelot#2]
Some URLS in Oscelot's context menu leads to 404 errors.

• When clicking on the link to read the changelog from within VCV Rack's Library menu when there is an update leads to a 404.

• Right clicking on the module and selecting Plugin > Manual leads to a 404.

• There is another link in the top level of that context menu that also leads to the page correctly. The placement of this entry seems unconventional as most other modules have the links to their manual pages within the Plugin section.

**Comment by The-Modular-Mind** [comment]
Thanks for the issue, this is because of the version  numbers being mismatched.

**Comment by The-Modular-Mind** [comment]
Fixed in 5deb90c3946582c9e69ec8ae65b0d62cf25e7169
