### ISSUE TITLE
V2 crashing Rack

### ISSUE THREAD

**Issue by pgatt** [The-Modular-Mind/oscelot#3]
Hi there, 

Don't know if you want to know yet, but your V2 test build from the community forum crashes Rack on opening the module browser. On Mac here.

**Comment by The-Modular-Mind** [comment]
Hmm I haven't tested on mac. Does Midi-Map/Midi-Cat work fine for you

**Comment by The-Modular-Mind** [comment]
Also have you compiled plugins before? Could you try compiling it  and see if the behavior still exists if so

**Comment by vernaillen** [comment]
I have the same issue on Mac.  Also after compiling from the latest commit.

It seems to be a common thing on Mac with newly ported modules. There's this thread including links to the fix commits in the Delexander repo: https://github.com/Delexander/Volume1/issues/18#issuecomment-961646415
Maybe that's helpful?

I'm not a C++ developer myself, but I did manage to set up the build environment on Mac, so I can help you test if you want.

**Comment by The-Modular-Mind** [comment]
Ah great thank you, I don't have a personal macbook so I've been only compiling it on GitHub. I'll take a look at  that thread and see if I can fix it later today. Thank you for your help

**Comment by The-Modular-Mind** [comment]
Ok I think I fixed it, can you please try when you get a chance:
https://github.com/The-Modular-Mind/oscelot/releases/tag/latest

**Comment by The-Modular-Mind** [comment]
Actually I left some test code in and broke it, another version is building right now.

**Comment by The-Modular-Mind** [comment]
The fixed builds are now available: https://github.com/The-Modular-Mind/oscelot/releases/tag/latest

**Comment by pgatt** [comment]
Yeah that fix seems to have done it here.
